name: citronix
services:
  sonar:
    container_name: citronix-sonarqube
    image: sonarqube:10.3.0-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - "127.0.0.1:9001:9000"
  postgres:
    image: postgres:17
    container_name: citronix-postgres
    environment:
      POSTGRES_DB: citronix
      POSTGRES_USER: citronix
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  sonar_data:
    driver: local
  postgres_data:
    driver: local
