spring:
  docker:
    compose:
      file: src/main/docker/docker-compose.yaml
      enabled: true
      lifecycle-management: start_only
      environment:
        DOCKER_API_VERSION: "1.46"
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: citronixmaroc@gmail.com
    password: zdpyuiuruwxicoem
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8083

