spring:
  docker:
    compose:
      file: src/main/docker/docker-compose.yaml
      enabled: true
      lifecycle-management: start_only
  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    change-log: db/changelog/changelog-master.yaml
    enabled: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8083

